package com.fdzang.microservice.data.dao.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table api_module_rel
 */
public class ApiModuleRelDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_module_rel.apiId
     *
     * @mbg.generated
     */
    private Integer apiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_module_rel.moduleId
     *
     * @mbg.generated
     */
    private Integer moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_module_rel.createTime
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column api_module_rel.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_module_rel.apiId
     *
     * @return the value of api_module_rel.apiId
     *
     * @mbg.generated
     */
    public Integer getApiId() {
        return apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_module_rel.apiId
     *
     * @param apiId the value for api_module_rel.apiId
     *
     * @mbg.generated
     */
    public void setApiId(Integer apiId) {
        this.apiId = apiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_module_rel.moduleId
     *
     * @return the value of api_module_rel.moduleId
     *
     * @mbg.generated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_module_rel.moduleId
     *
     * @param moduleId the value for api_module_rel.moduleId
     *
     * @mbg.generated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_module_rel.createTime
     *
     * @return the value of api_module_rel.createTime
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_module_rel.createTime
     *
     * @param createTime the value for api_module_rel.createTime
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column api_module_rel.updateTime
     *
     * @return the value of api_module_rel.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column api_module_rel.updateTime
     *
     * @param updateTime the value for api_module_rel.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}