server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://120.78.121.110:7001/eureka/,http://http://120.78.121.110:7002/eureka/,http://http://120.78.121.110:7003/eureka/

spring:
  application:
    name: api-gateway

auth:
  gateway:
    white:
    - /login