server:
  port: 7000

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7003/eureka/
      #      defaultZone: http://120.78.121.110:7001/eureka/,http://http://120.78.121.110:7002/eureka/,http://http://120.78.121.110:7003/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: gateway
          uri: http://www.baidu.com
          predicates:
            - Path=/**

auth:
  service-id: api-auth-v1
  gateway:
    white:
      - /login


IdWorker:
  workerId: 122
  datacenterId: 1231