package com.fdzang.microservice.ucenter.dao.domain;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_module
 */
public class UserModuleDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.userId
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.moduleId
     *
     * @mbg.generated
     */
    private Integer moduleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.accessId
     *
     * @mbg.generated
     */
    private String accessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.secret
     *
     * @mbg.generated
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.applyTime
     *
     * @mbg.generated
     */
    private Date applyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.auditTime
     *
     * @mbg.generated
     */
    private Date auditTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.expireTime
     *
     * @mbg.generated
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_module.updateTime
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.id
     *
     * @return the value of user_module.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.id
     *
     * @param id the value for user_module.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.userId
     *
     * @return the value of user_module.userId
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.userId
     *
     * @param userId the value for user_module.userId
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.moduleId
     *
     * @return the value of user_module.moduleId
     *
     * @mbg.generated
     */
    public Integer getModuleId() {
        return moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.moduleId
     *
     * @param moduleId the value for user_module.moduleId
     *
     * @mbg.generated
     */
    public void setModuleId(Integer moduleId) {
        this.moduleId = moduleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.accessId
     *
     * @return the value of user_module.accessId
     *
     * @mbg.generated
     */
    public String getAccessId() {
        return accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.accessId
     *
     * @param accessId the value for user_module.accessId
     *
     * @mbg.generated
     */
    public void setAccessId(String accessId) {
        this.accessId = accessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.secret
     *
     * @return the value of user_module.secret
     *
     * @mbg.generated
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.secret
     *
     * @param secret the value for user_module.secret
     *
     * @mbg.generated
     */
    public void setSecret(String secret) {
        this.secret = secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.status
     *
     * @return the value of user_module.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.status
     *
     * @param status the value for user_module.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.applyTime
     *
     * @return the value of user_module.applyTime
     *
     * @mbg.generated
     */
    public Date getApplyTime() {
        return applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.applyTime
     *
     * @param applyTime the value for user_module.applyTime
     *
     * @mbg.generated
     */
    public void setApplyTime(Date applyTime) {
        this.applyTime = applyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.auditTime
     *
     * @return the value of user_module.auditTime
     *
     * @mbg.generated
     */
    public Date getAuditTime() {
        return auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.auditTime
     *
     * @param auditTime the value for user_module.auditTime
     *
     * @mbg.generated
     */
    public void setAuditTime(Date auditTime) {
        this.auditTime = auditTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.expireTime
     *
     * @return the value of user_module.expireTime
     *
     * @mbg.generated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.expireTime
     *
     * @param expireTime the value for user_module.expireTime
     *
     * @mbg.generated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_module.updateTime
     *
     * @return the value of user_module.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_module.updateTime
     *
     * @param updateTime the value for user_module.updateTime
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}