package com.fdzang.microservice.data.dao.mapper;

import com.fdzang.microservice.data.dao.domain.ApiModuleRelDO;
import com.fdzang.microservice.data.dao.domain.ApiModuleRelDOExample;
import java.util.List;

public interface ApiModuleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_module_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer apiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_module_rel
     *
     * @mbg.generated
     */
    int insert(ApiModuleRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_module_rel
     *
     * @mbg.generated
     */
    int insertSelective(ApiModuleRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_module_rel
     *
     * @mbg.generated
     */
    List<ApiModuleRelDO> selectByExample(ApiModuleRelDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_module_rel
     *
     * @mbg.generated
     */
    ApiModuleRelDO selectByPrimaryKey(Integer apiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_module_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApiModuleRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table api_module_rel
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApiModuleRelDO record);
}