package com.fdzang.microservice.ucenter.dao.mapper;

import com.fdzang.microservice.ucenter.dao.domain.UserModuleDO;
import com.fdzang.microservice.ucenter.dao.domain.UserModuleDOExample;
import java.util.List;

public interface UserModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_module
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_module
     *
     * @mbg.generated
     */
    int insert(UserModuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_module
     *
     * @mbg.generated
     */
    int insertSelective(UserModuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_module
     *
     * @mbg.generated
     */
    List<UserModuleDO> selectByExample(UserModuleDOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_module
     *
     * @mbg.generated
     */
    UserModuleDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserModuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_module
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserModuleDO record);
}